name: CI

on:
  push:
  pull_request:

env:
# on CI, better dump stack trace in case there is an error
  PLUMED_STACK_TRACE: yes
# use two threads for openMP tests
  PLUMED_NUM_THREADS: 2
# these are used to build required packages
  CC: gcc
  CXX: g++

jobs:
  # We test on centos7 to make sure we have compatibility with older compilers (gcc 4.8)
  centos7:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests
      run: |
        make -C docker centos7

  # We test on fedora37 to make sure we have compatibility with newer compilers (gcc 12)
  fedora37:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests
      run: |
        make -C docker fedora37

  # We test on rockylinux8 as well
  rocky8:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests
      run: |
        make -C docker rocky8
