name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install generic packages
      run: |
        sudo apt-get install -y gawk
        sudo apt-get install -y binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
    - name: Build PLUMED
      run: |
        ./configure --host=x86_64-w64-mingw32
        make -j 4
        ls -ltr src/lib
        file src/lib/plumed.exe
    - uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: src/lib/plumed.exe
