name: Docker

on:
  push:
  pull_request:

jobs:
  centos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        make -C docker
    - name: Run tests
      run: |
        make -C docker
        docker run -v "$PWD/regtest":/home/plumed/regtest -it plumed /bin/bash -c "make -C regtest"
